### ISSUE TITLE
Is there a code sample or a tutorial for beginners somewhere?

### ISSUE THREAD

**Issue by b1tkeeper** [hillu/go-yara#105]
I can't simply use go-yara like I can with yara-python，Is there a code sample or a tutorial for beginners somewhere?

**Comment by hillu** [comment]
Sure. Please have a look at the `_examples/simple-yara` directory.

Is there anything else you need to get started … or do you have suggestions on how to improve the documentation?

**Comment by b1tkeeper** [comment]
> 
Even I appreciate It's not particularly easy to use than yara-python


> Sure. Please have a look at the `_examples/simple-yara` directory.
> 
> Is there anything else you need to get started … or do you have suggestions on how to improve the documentation?

So much appreciate for your reply, I'm sorry to say, go-yara is not particularlly easy to use than yara-python.....，You'd better to optimize the API.

I sincerely hope that go-yara can grow and grow

**Comment by hillu** [comment]
At the moment, I don't think that there is anything to be done to improve the API. Since Go is a language based on weak static types, the experience is going to be a bit different from what you get with Python. (I had a brief look at Go 1.18+ "generics", but there wasn't anything that could have been improved by usinig generiics.)

So, if there's anything that can be improved regarding examples or other documentation, please tell me.

**Comment by hillu** [comment]
@aosti Thank you for your feedback. :-)

@b1tkeeper: Unless you have any specific suggestions on what to improve (preferably in the form of pull requests), I'm going to close this issue.

**Comment by hillu** [comment]
Since there are no specific suggestions on what to improve, I'm closing this issue.
