### ISSUE TITLE
Shippable binary for OSX

### ISSUE THREAD

**Issue by zoid42** [hillu/go-yara#95]
Hi, 

is there a recommended way of including go-yara and the yara lib in a single binary for OSX? 
Ideally a single binary, alternatively a static lib that sits next to the application using it.  I would like to avoid having to install yara on the systems that runs applications that uses go-yara

thanks for any help or pointers 
Peter

**Comment by hillu** [comment]
I seem to remember that there's no way to explicitly tell the linker that it should do a static build, so one has to get make sure it only finds `libyara.a`, not the `.dylib` file. The build system for [Spyre](https://github.com/spyre-project/spyre) does this: It builds C dependencies (on MacOSX: OpenSSL, YARA) from source and subsequently gets rid of shared libraries.

(Perhaps this has changed since I last tried, but I can't try since I don't have acces to a MacOSX dev environment at the moment.) The `libc` still has to be linked dynamically, there's no supported way to do an entirely static build.

Does this help?

**Comment by zoid42** [comment]
I am not very experienced with building c libs and deploying them. The go app I build seems to have a hard requirement of loading /usr/local/lib/libyara.8.dylib  -- so maybe my question is, is there anything I can change in the build process of the go app that causes it not to expect a .dylib file in /usr/local/lib but instead a libyara.a file next to the built binary ? 

I have tried to remove /usr/local/lib/libyara.8.dylib and place libyara.a next to the binary, but it will produce an error : "dyld: Library not loaded: /usr/local/lib/libyara.8.dylib"

otool reports this for my binary

`[app] otool -L myapp                                                                                                                              main
myapp:
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1122.33.0)
	/usr/local/lib/libyara.8.dylib (compatibility version 9.0.0, current version 9.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1775.118.101)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 59754.100.106)`

**Comment by hillu** [comment]
Like I said, I don't know how to tell the linker on MacOSX to ignore any shared libraries (`*.dylib`). However, if you remove or rename your `/usr/local/lib/libyara.8.dylib` so that `ld` does not find it when building, it should use `libyara.a` instead, resulting in a partially static build.

**Comment by hillu** [comment]
@zoid42 Did this help?

**Comment by hillu** [comment]
@zoid42 ping?

**Comment by hillu** [comment]
No answer -> closing this issue. Feel free to reopen if there are any questions.
